version: "3.9"

services:
  evolution-api:
    container_name: evolution_api
    image: atendai/evolution-api:v2.1.1
    restart: always
    ports:
      - "8080:8080"
    environment:
      # Ganti dengan API key acak punyamu — ini yang dipakai untuk semua request ke Evolution API.
      # Bisa generate string acak lewat: openssl rand -hex 32
      - AUTHENTICATION_API_KEY=15f30219224aec287d3c51840f5695d451bd4dc7cbab92ff76eeeae7aa46031c
    volumes:
      - evolution_instances:/evolution/instances

volumes:
  evolution_instances: